version: '3'
services:
  elasticsearch:
    build: ./elastic
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic/readonlyrest.yml:/usr/share/elasticsearch/config/readonlyrest.yml
    ports:
      - 9400:9200
      - 9600:9300
    restart: always
    networks:
      - esnet
  elasticsearch2:
    build: ./elastic
    container_name: elasticsearch2
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic/readonlyrest.yml:/usr/share/elasticsearch/config/readonlyrest.yml
    restart: always
    networks:
      - esnet
#  elasticsearch3:
#    build: ./elastic
#    container_name: elasticsearch3
#    environment:
#      - node.name=es03
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#    ulimits:
#      nproc: 65535
#      memlock:
#        soft: -1
#        hard: -1
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 10s
#    volumes:
#      - ./volumes/esdata3:/usr/share/elasticsearch/data
#      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elastic/readonlyrest.yml:/usr/share/elasticsearch/config/readonlyrest.yml
#    restart: always
#    networks:
#      - esnet

volumes:
  esdata1:
  esdata2:
#  esdata3:

networks:
  esnet:
